apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netflix-clone

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: netflix-clone
  version: v1.0.0 