apiVersion: v1
kind: Secret
metadata:
  name: netflix-clone-secrets
  namespace: netflix-clone
type: Opaque
data:
  # Base64 encoded TMDB API key - replace with your actual encoded key
  # echo -n "your-tmdb-api-key" | base64
  VITE_APP_TMDB_V3_API_KEY: eW91ci10bWRiLWFwaS1rZXktaGVyZQ== 